(()=>{'use strict';
const c=window.MT_CONFIG, $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
let msal,account,items=[],etag=null,tab='dashboard',busy=false;
const ready=()=>c.clientId&&!c.clientId.startsWith('REPLACE')&&c.tenantId&&!c.tenantId.startsWith('REPLACE')&&c.driveId&&!c.driveId.startsWith('REPLACE')&&c.folderItemId&&!c.folderItemId.startsWith('REPLACE');
const owner=()=>c.adminEmails.map(x=>x.toLowerCase()).includes((account?.username||'').toLowerCase());
const folderPath=()=>`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(c.driveId)}/items/${encodeURIComponent(c.folderItemId)}`;
const filePath=()=>`${folderPath()}:/${encodeURIComponent(c.fileName)}:`;
function status(s,error=false){$(error?'error':'status').textContent=s;if(!error)$('error').textContent='';}
async function token(){const req={scopes:['User.Read','Files.ReadWrite.All'],account};try{return (await msal.acquireTokenSilent(req)).accessToken}catch(e){return (await msal.acquireTokenPopup(req)).accessToken}}
async function graph(url,options={}){const headers={Authorization:'Bearer '+await token(),...(options.headers||{})};const res=await fetch(url,{...options,headers});if(!res.ok){let detail='';try{detail=(await res.json()).error?.message||''}catch{}throw Error(`Microsoft Graph ${res.status}: ${detail||res.statusText}`)}return res}
async function load(){if(!account)return;busy=true;status('กำลังอ่านข้อมูล OneDrive...');try{const meta=await graph(filePath());const info=await meta.json();etag=info.eTag;const resp=await graph(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(c.driveId)}/items/${encodeURIComponent(info.id)}/content`);const data=await resp.json();if(!Array.isArray(data.tasks))throw Error('ไฟล์ข้อมูลไม่ถูกต้อง');items=data.tasks;status('ซิงก์ล่าสุด: '+new Date().toLocaleString('th-TH'))}catch(e){if(/Graph 404/.test(e.message)){items=[];etag=null;status('ยังไม่มีไฟล์ข้อมูล: Admin สามารถสร้างงานแรกเพื่อเริ่มต้นได้')}else status(e.message,true)}finally{busy=false;render()}}
async function save(next){if(busy)return;busy=true;status('กำลังบันทึก...');try{const payload=JSON.stringify({schema:1,updatedAt:new Date().toISOString(),tasks:next},null,2);let headers={'Content-Type':'application/json'};if(etag){headers['If-Match']=etag}else{headers['If-None-Match']='*'};await graph(filePath()+'/content',{method:'PUT',headers,body:payload});items=next;status('บันทึกแล้ว กำลังตรวจสอบข้อมูลล่าสุด...');await load()}catch(e){status('บันทึกไม่สำเร็จ: '+e.message+' — กรุณา Sync ก่อนแก้ไขอีกครั้ง',true)}finally{busy=false;render()}}
function render(){const view=$('view');document.querySelectorAll('nav button').forEach(b=>b.disabled=!account);$('reload').disabled=!account;$('logout').disabled=!account;$('login').disabled=!!account;if(!account){view.innerHTML='<p>Login ด้วยบัญชี Microsoft 365 เพื่อเข้าถึงข้อมูลที่ได้รับสิทธิ์</p>';return}
if(tab==='dashboard'){const count=s=>items.filter(x=>x.status===s).length;view.innerHTML=`<h3>Dashboard</h3><p>ทั้งหมด <b>${items.length}</b> | Pending ${count('Pending')} | In Progress ${count('In Progress')} | Completed ${count('Completed')}</p><p>Overdue: ${items.filter(x=>x.due&&x.due<new Date().toISOString().slice(0,10)&&x.status!=='Completed').length}</p>`}
if(tab==='tasks'){view.innerHTML=`<h3>Tasks</h3><form id="add"><label>ชื่องาน <input name="title" required maxlength="160"></label><label>ประเภท <select name="category"><option>Daily Operations</option><option>Project Response</option><option>Process Improvement</option></select></label><label>ผู้รับผิดชอบ <input name="assignee" value="${esc(account.name||account.username)}" required></label><label>Start <input name="start" type="date"></label><label>Due <input name="due" type="date"></label><button>เพิ่มงาน</button></form><div style="overflow:auto"><table><thead><tr><th>งาน</th><th>ประเภท</th><th>ผู้รับผิดชอบ</th><th>Due</th><th>สถานะ</th><th>Comments</th></tr></thead><tbody>${items.map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.category)}</td><td>${esc(t.assignee)}</td><td>${esc(t.due)}</td><td><select data-id="${esc(t.id)}" class="task-status">${['Pending','In Progress','Completed'].map(s=>`<option ${t.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${(t.comments||[]).length} <button class="comment" data-id="${esc(t.id)}">+</button></td></tr>`).join('')}</tbody></table></div>`;view.querySelector('#add').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const t={id:crypto.randomUUID(),title:f.get('title'),category:f.get('category'),assignee:f.get('assignee'),start:f.get('start'),due:f.get('due'),status:'Pending',comments:[],createdBy:account.username};await save([...items,t])};view.querySelectorAll('.task-status').forEach(s=>s.onchange=()=>save(items.map(t=>t.id===s.dataset.id?{...t,status:s.value}:t)));view.querySelectorAll('.comment').forEach(b=>b.onclick=()=>{const value=prompt('ความคิดเห็น');if(value?.trim())save(items.map(t=>t.id===b.dataset.id?{...t,comments:[...(t.comments||[]),{by:account.username,text:value.trim(),at:new Date().toISOString()}]}:t))})}
if(tab==='calendar'){const groups={};items.forEach(t=>{const d=t.due||'No due date';(groups[d]??=[]).push(t)});view.innerHTML='<h3>Calendar (ตาม Due Date)</h3>'+Object.keys(groups).sort().map(d=>`<h4>${esc(d)}</h4><p>${groups[d].map(t=>esc(t.title)).join(' · ')}</p>`).join('')}
if(tab==='gantt'){view.innerHTML='<h3>Gantt / Timeline</h3>'+items.filter(t=>t.start&&t.due).map(t=>`<p><b>${esc(t.title)}</b> — ${esc(t.start)} → ${esc(t.due)} (${esc(t.status)})</p>`).join('')}
if(tab==='admin'){view.innerHTML=owner()?`<h3>Admin</h3><p>สิทธิ์ Admin กำหนดจากอีเมลใน config.js และสิทธิ์ OneDrive</p><p>การเพิ่มสมาชิก: แชร์โฟลเดอร์ OneDrive ให้บัญชีบริษัทของสมาชิก และเพิ่มอีเมล Admin ใน config.js ก่อนเผยแพร่ใหม่</p><button id="export">Export CSV</button>`:'<p>เฉพาะ Admin</p>';if(owner())$('export').onclick=()=>{const lines=[['Task','Category','Assignee','Start','Due','Status'],...items.map(t=>[t.title,t.category,t.assignee,t.start,t.due,t.status])];const csv='\ufeff'+lines.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='MT56251_Tasks.csv';a.click();URL.revokeObjectURL(a.href)}}}
async function init(){if(!ready()){status('กรุณากรอกค่าใน config.js และลงทะเบียนแอป Microsoft Entra ID ก่อน',true);$('login').disabled=true;render();return}if(!window.msal){status('โหลด Microsoft Login library ไม่สำเร็จ ตรวจสอบอินเทอร์เน็ต',true);$('login').disabled=true;return}msal=new window.msal.PublicClientApplication({auth:{clientId:c.clientId,authority:`https://login.microsoftonline.com/${c.tenantId}`,redirectUri:location.origin+location.pathname},cache:{cacheLocation:'sessionStorage'}});await msal.handleRedirectPromise();account=msal.getAllAccounts()[0]||null;if(account){$('identity').textContent=account.username;await load()}else render()}
$('login').onclick=async()=>{try{const r=await msal.loginPopup({scopes:['User.Read','Files.ReadWrite.All']});account=r.account;$('identity').textContent=account.username;await load()}catch(e){status('Login ไม่สำเร็จ: '+e.message,true)}};$('logout').onclick=async()=>{await msal.logoutPopup({account});account=null;items=[];etag=null;$('identity').textContent='ยังไม่ได้เข้าสู่ระบบ';render()};$('reload').onclick=load;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});init().catch(e=>status(e.message,true));})();
