(()=>{'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cfg=window.MT_CONFIG||{};let db=null,user=null,profile=null,tasks=[],members=[],commentTask=null,month=new Date(),channel=null;
const dateOnly=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const today=()=>dateOnly(new Date());const show=(id,yes)=>$(id).classList.toggle('hidden',!yes);
const msg=(s,bad=false)=>{$('notice').textContent=s;$('notice').className=bad?'error':'muted'};
function view(name){for(const id of ['dashboard','tasks','calendar','gantt','members','admin'])show(id,id===name);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));render();}
function memberName(id){const m=members.find(x=>x.id===id);return m?m.display_name||m.id.slice(0,8):'—'}
function table(items){return `<table><thead><tr><th>งาน</th><th>ประเภท</th><th>สถานะ</th><th>Progress</th><th>ผู้รับผิดชอบ</th><th>Due</th><th>จัดการ</th></tr></thead><tbody>${items.map(t=>`<tr><td><b>${esc(t.title)}</b><div class="muted">${esc(t.description).slice(0,120)}</div></td><td>${esc(t.category)}</td><td><span class="pill">${esc(t.status)}</span></td><td>${t.progress}%<div class="bar"><span style="width:${Number(t.progress)||0}%"></span></div></td><td>${esc(memberName(t.assigned_to))}</td><td>${esc(t.due_date||'—')}</td><td><button class="secondary" data-edit="${t.id}">แก้ไข</button> <button class="secondary" data-comment="${t.id}">Comments</button></td></tr>`).join('')}</tbody></table>`}
function render(){const total=tasks.length,done=tasks.filter(t=>t.status==='Completed').length,late=tasks.filter(t=>t.due_date&&t.due_date<today()&&t.status!=='Completed').length,doing=tasks.filter(t=>t.status==='In Progress').length;
$('metrics').innerHTML=[['Total Tasks',total],['In Progress',doing],['Completed',done],['Overdue',late]].map(([k,v])=>`<div class="metric"><small>${k}</small><strong>${v}</strong></div>`).join('');
$('upcoming').innerHTML=table(tasks.filter(t=>t.due_date&&t.status!=='Completed').sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,8));
const q=$('search').value.toLowerCase(),f=$('filter').value;$('taskTable').innerHTML=table(tasks.filter(t=>(!f||t.status===f)&&(!q||[t.title,t.description,t.category].some(x=>String(x||'').toLowerCase().includes(q)))));
$('memberTable').innerHTML=`<table><tr><th>ชื่อ</th><th>Role</th><th>สี</th></tr>${members.map(m=>`<tr><td>${esc(m.display_name||m.id.slice(0,8))}</td><td>${esc(m.role)}</td><td><span style="display:inline-block;width:18px;height:18px;border-radius:50%;background:${/^#[0-9a-f]{6}$/i.test(m.user_color)?m.user_color:'#2563eb'}"></span></td></tr>`).join('')}</table>`;
show('admin',!$('admin').classList.contains('hidden')&&profile?.role==='admin');document.querySelector('[data-view="admin"]').classList.toggle('hidden',profile?.role!=='admin');renderCalendar();renderGantt();}
function renderCalendar(){const y=month.getFullYear(),m=month.getMonth();$('monthTitle').textContent=month.toLocaleDateString('th-TH',{month:'long',year:'numeric'});const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let html=['อา','จ','อ','พ','พฤ','ศ','ส'].map(x=>`<div class="muted">${x}</div>`).join('');for(let i=0;i<first;i++)html+='<div></div>';for(let d=1;d<=days;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;html+=`<div class="day"><b>${d}</b>${tasks.filter(t=>t.due_date===key).map(t=>`<div class="event" title="${esc(t.title)}">${esc(t.title)}</div>`).join('')}</div>`}$('calendarGrid').innerHTML=html;}
function renderGantt(){const days=Array.from({length:14},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return dateOnly(d)});let h=`<div>Task</div>${days.map(d=>`<div>${d.slice(5)}</div>`).join('')}`;for(const t of tasks.filter(x=>x.start_date&&x.due_date)){h+=`<div title="${esc(t.title)}">${esc(t.title)}</div>`+days.map(d=>`<div class="${d>=t.start_date&&d<=t.due_date?'filled':''}">${d===t.start_date?'●':''}</div>`).join('')}$('ganttGrid').innerHTML=`<div class="gantt">${h}</div>`;}
async function refresh(){if(!user)return;const [tr,mr,pr]=await Promise.all([db.from('tasks').select('*').order('created_at',{ascending:false}),db.from('profiles').select('id,display_name,role,user_color'),db.from('profiles').select('id,role,display_name').eq('id',user.id).single()]);if(tr.error||mr.error||pr.error){msg('โหลดข้อมูลไม่สำเร็จ: '+[tr.error,mr.error,pr.error].filter(Boolean).map(e=>e.message).join(' / '),true);return}tasks=tr.data||[];members=mr.data||[];profile=pr.data;$('identity').textContent=`${profile.display_name||user.email} (${profile.role})`;render();}
async function signedIn(u){user=u;show('auth',!u);show('app',!!u);show('logout',!!u);show('setup',false);if(channel){await db.removeChannel(channel);channel=null}if(u){await refresh();channel=db.channel('mt56251-updates').on('postgres_changes',{event:'*',schema:'public',table:'tasks'},()=>refresh()).on('postgres_changes',{event:'*',schema:'public',table:'comments'},()=>{if(commentTask)loadComments()}).subscribe();}}
function openTask(id){const t=tasks.find(x=>x.id===id);$('taskForm').reset();$('taskId').value=t?.id||'';$('dialogTitle').textContent=t?'แก้ไขงาน':'เพิ่มงาน';for(const k of ['title','description','category','status','progress','start_date','due_date'])if(t&&t[k]!=null)$(k).value=t[k];$('assigned_to').innerHTML='<option value="">ไม่ระบุ</option>'+members.map(m=>`<option value="${m.id}">${esc(m.display_name||m.id.slice(0,8))}</option>`).join('');$('assigned_to').value=t?.assigned_to||'';$('taskMsg').textContent='';$('taskDialog').showModal();}
async function loadComments(){if(!commentTask)return;const {data,error}=await db.from('comments').select('*').eq('task_id',commentTask).order('created_at');$('commentsList').innerHTML=error?esc(error.message):(data||[]).map(c=>`<p><b>${esc(memberName(c.author_id))}</b> <small>${new Date(c.created_at).toLocaleString('th-TH')}</small><br>${esc(c.message)}</p>`).join('')||'<p class="muted">ยังไม่มีความคิดเห็น</p>';}
async function openComments(id){commentTask=id;$('commentTitle').textContent='Comments: '+(tasks.find(t=>t.id===id)?.title||'');$('commentMsg').textContent='';$('commentsDialog').showModal();await loadComments();}
async function boot(){if(!window.supabase||!cfg.supabaseUrl||!cfg.publishableKey||cfg.publishableKey.includes('PASTE_')){$('setupMsg').textContent='ยังไม่ได้ใส่ Publishable Key ใน config.js หรือโหลด Supabase library ไม่สำเร็จ';return}db=window.supabase.createClient(cfg.supabaseUrl,cfg.publishableKey);const {data,error}=await db.auth.getSession();if(error)console.warn(error);await signedIn(data?.session?.user||null);db.auth.onAuthStateChange((_event,session)=>{if(session?.user?.id!==user?.id)void signedIn(session?.user||null)});}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='กำลังเข้าสู่ระบบ...';const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('loginMsg').textContent=error?error.message:'';};
$('forgot').onclick=async()=>{const email=$('email').value.trim();if(!email){$('loginMsg').textContent='กรอก Email ก่อน';return}const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('loginMsg').textContent=error?error.message:'หากบัญชีนี้มีอยู่ ระบบจะส่งอีเมลรีเซ็ต (ต้องตั้งค่า URL ใน Supabase ก่อน)';};
$('logout').onclick=()=>db.auth.signOut();document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));$('newTask').onclick=()=>openTask(null);$('cancelTask').onclick=()=>$('taskDialog').close();$('search').oninput=render;$('filter').onchange=render;
$('taskForm').onsubmit=async e=>{e.preventDefault();const id=$('taskId').value;const data={title:$('title').value.trim(),description:$('description').value,category:$('category').value,status:$('status').value,progress:Number($('progress').value),start_date:$('start_date').value||null,due_date:$('due_date').value||null,assigned_to:$('assigned_to').value||null};if(data.start_date&&data.due_date&&data.start_date>data.due_date){$('taskMsg').textContent='Due Date ต้องไม่ก่อน Start Date';return}const result=id?await db.from('tasks').update(data).eq('id',id):await db.from('tasks').insert({...data,created_by:user.id});if(result.error){$('taskMsg').textContent=result.error.message;return}$('taskDialog').close();await refresh();};
document.addEventListener('click',e=>{const a=e.target.closest('[data-edit]'),b=e.target.closest('[data-comment]');if(a)openTask(a.dataset.edit);if(b)openComments(b.dataset.comment)});$('closeComments').onclick=()=>{$('commentsDialog').close();commentTask=null};$('commentForm').onsubmit=async e=>{e.preventDefault();const message=$('commentText').value.trim();if(!message)return;const {error}=await db.from('comments').insert({task_id:commentTask,author_id:user.id,message});if(error){$('commentMsg').textContent=error.message;return}$('commentText').value='';await loadComments();};
$('prevMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);renderCalendar()};
$('export').onclick=()=>{const cols=['title','description','category','status','progress','start_date','due_date','assigned_to','created_at'];const csv='\ufeff'+[cols.join(','),...tasks.map(t=>cols.map(k=>'"'+String(t[k]??'').replace(/"/g,'""')+'"').join(','))].join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MT56251_Tasks_'+today()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
boot().catch(e=>{$('setupMsg').textContent=e.message;show('setup',true)});
})();
